### ISSUE TITLE
打开应用就闪退，日志如下(魅族魅蓝3S-Flyme6)

### ISSUE THREAD

**Issue by naloder** [iMeiji/Toutiao#1]
05-12 18:24:13.371  7262  7262 E AndroidRuntime: FATAL EXCEPTION: main
05-12 18:24:13.371  7262  7262 E AndroidRuntime: Process: com.meiji.toutiao, PID: 7262
05-12 18:24:13.371  7262  7262 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getColor(ILandroid/content/res/Resources$Theme;)I in class Landroid/content/res/Resources; or its super classes (declaration of 'android.content.res.Resources' appears in /system/framework/framework.jar)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at com.meiji.toutiao.module.base.BaseActivity.onResume(Unknown Source)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at com.meiji.toutiao.MainActivity.onResume(Unknown Source)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1286)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6286)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3418)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3471)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2780)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:189)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:194)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5883)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
05-12 18:24:13.371  7262  7262 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by iMeiji** [comment]
感谢提供日志 新版已修复
