### ISSUE TITLE
有关于5.0系统以下出现java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by weimi-king** [iMeiji/Toutiao#10]
5.0以下或部分机型，会出现NoClassDefFoundError异常crash，原因是方法数已经超出了65535，导致部分方法导入了第二个dex文件中。
解决方法：
1.在build中增加 implementation 'com.android.support:multidex:1.0.1'
2.InitApp类继承MultiDexApplication类
适配5.0以下机型。

**Comment by iMeiji** [comment]
@weimi-king thanks
