### ISSUE TITLE
gradle3.3无法编译

### ISSUE THREAD

**Issue by createBean** [iMeiji/Toutiao#12]
你好，我看到你的项目中是用到gradle4.4 Android studio3.0    但放到我的studio中编译是报错的。这个应该是怎么解决的呢 
![image](https://user-images.githubusercontent.com/17917032/32759105-54e0f264-c8ad-11e7-996f-b1ce64f3bfa7.png)

**Comment by xq598359628** [comment]
同问

**Comment by iMeiji** [comment]
@createBean @xq598359628 使用的是 AS 2.3 版本？

**Comment by createBean** [comment]
是的， 我的as2.3  gradle3.3

**Comment by naruto1019** [comment]
项目是用as3.0编译的  用2.3的编译把build.gradle配置改下就行了
![default](https://user-images.githubusercontent.com/18226174/32761913-1e98f22c-c931-11e7-8545-86b84dea8d48.png)
![default](https://user-images.githubusercontent.com/18226174/32761934-40d13372-c931-11e7-898b-11f53088a1ee.png)

**Comment by iMeiji** [comment]
as 2.3 可参考这个 commit 修改 gradle 文件
https://github.com/iMeiji/Toutiao/commit/7dbca96b8944f2897f7c0026f4bce71cc5edc3c8

**Comment by iMeiji** [comment]
另外 as 2.3 也是可以添加 Google 仓库 , 不添加 support 库只能用 25.3.1
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://maven.google.com" }
    }
}

```

**Comment by createBean** [comment]
亲测有效，照着这位兄台的改@naruto1019
