### ISSUE TITLE
配置文件合并失败究竟是.....

### ISSUE THREAD

**Issue by Davy103** [iMeiji/Toutiao#17]
楼主你好，编译完成的时候出现这个错误
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

点进去显示的具体错误信息如下：Merging Errors: Error: tools:replace specified at line:26 for attribute android:value, but no new value specified app main manifest (this file), line 25 Error: Validation failed, exiting app main manifest (this file)

有什么好的解决办法嘛

**Comment by AdamShirlyZhang** [comment]
弄了一上午，终于解决冲突了，我是在AS2.3.3上编译的，
下面是完成的build.gradle文件

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.0'

    defaultConfig {
        applicationId "com.meiji.toutiao"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 13
        versionName "1.3.1"
        multiDexEnabled true
//        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled true  //设为false即可断点调试
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    //    compile "com.android.support:appcompat-v7:$SUPPORT_LIBRARY_VERSION"
    compile 'com.android.support:cardview-v7:26.0.0-alpha1'
    compile 'com.android.support:design:26.0.0-alpha1'
    compile 'com.android.support:customtabs:26.0.0-alpha1'
    //    compile 'com.android.support:support-v4:25.3.0'
    //    compile "com.android.support:recyclerview-v7:$SUPPORT_LIBRARY_VERSION"
    // 解析JSON
    //    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.google.code.gson:gson:2.8.0'
    // 图片加载
    compile 'com.github.bumptech.glide:glide:3.7.0'
    // 解析HTML
    compile 'org.jsoup:jsoup:1.10.1'
    // 图片浏览
    compile 'com.github.chrisbanes.photoview:library:1.2.4'
    // 协议Dialog
    compile 'de.psdev.licensesdialog:licensesdialog:1.8.2'
    // 节操播放器
    compile 'fm.jiecao:jiecaovideoplayer:5.7'
    // retrofit 2
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-gson:2.2.0'
    compile 'com.squareup.retrofit2:adapter-rxjava2:2.2.0'
    // 持久化 Cookie
    compile 'com.github.franmontiel:PersistentCookieJar:v1.0.1'
    // RxJava 2
    compile 'io.reactivex.rxjava2:rxjava:2.0.9'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    // RxLifecycle
    compile 'com.trello.rxlifecycle2:rxlifecycle:2.0.1'
    compile 'com.trello.rxlifecycle2:rxlifecycle-components:2.0.1'
    // okhttp 3
    compile 'com.squareup.okhttp3:okhttp:3.7.0'
    debugCompile 'com.squareup.okhttp3:logging-interceptor:3.7.0'
    debugCompile 'com.squareup.okhttp3:logging-interceptor:3.9.0'
    // MD dialog
    compile 'com.afollestad.material-dialogs:commons:0.9.4.4'
    // 权限管理
    compile('com.github.hotchemi:permissionsdispatcher:2.4.0') { exclude module: 'support-v13' }
    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.4.0'
    // 调试工具
    debugCompile 'com.facebook.stetho:stetho:1.5.0'
    testCompile 'junit:junit:4.12'
    // 简化版 Adapter
    compile 'me.drakeet.multitype:multitype:3.0.0'
    // RxBinding
    compile 'com.jakewharton.rxbinding2:rxbinding-appcompat-v7:2.0.0'
    // 响应式排版布局
    compile 'com.google.android:flexbox:0.2.7'
    // 滑动返回 https://oss.sonatype.org/content/repositories/snapshots/com/r0adkll/slidableactivity/
    compile 'com.r0adkll:slidableactivity:2.0.7-SNAPSHOT'
    // 带刻度的 SeekBar
    compile 'com.github.Jay-Goo:RangeSeekBar:v1.0.7'
    // 高亮功能提示效果 https://material.google.com/growth-communications/feature-discovery.html#feature-discovery-design
    compile 'com.getkeepsafe.taptargetview:taptargetview:1.9.1'
//    compile 'com.android.support:support-v4:26.0.0-alpha1'
    compile('com.android.support:appcompat-v7:26.0.0-alpha1') {
        exclude group: 'com.android.support'
    }

//    compile 'com.android.support:support-v13:26.0.0-alpha1'
}

configurations.all {

    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.0.0-alpha1'//默认使用的版本
            }
        }
    }
}
