### ISSUE TITLE
怎么我的as跑起来报错了

### ISSUE THREAD

**Issue by Davy103** [iMeiji/Toutiao#18]
楼主好，小弟安卓新手，在运行你项目的时候，所有控件初始化的时候，都报强转类型出错，
比如 ：Toutiao-master\app\src\main\java\com\meiji\toutiao\adapter\photo\PhotoContentAdapter.java
Error:(57, 57) 错误: 不兼容的类型: View无法转换为ImageView
类似这样的，好奇怪，是我as版本低了吗？

**Comment by iMeiji** [comment]
@Davy103 https://github.com/iMeiji/Toutiao/issues/4

**Comment by Davy103** [comment]
好的，我这边26跑不来了，所以降到25了。
