### ISSUE TITLE
一直编译不通过，gradel是4.1，as是3.0

### ISSUE THREAD

**Issue by catroom** [iMeiji/Toutiao#24]
有人可以编译运行吗，我注释掉gradle.properties的proxyHost也还是不行。有同学编译成功的话可以告知我一下，谢谢

**Comment by dudukee** [comment]
可以编译成功
AS3.0
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
classpath 'com.android.tools.build:gradle:3.0.0'

**Comment by catroom** [comment]
谢谢了，我编译通过了，默认会在build gradle增加google（），而且删掉gradle里面的4.2.1，用本地的4.1.完美运行，谢谢
