### ISSUE TITLE
感谢作者开源供大家学习，关于底栏导航想请教下

### ISSUE THREAD

**Issue by jayleco** [iMeiji/Toutiao#26]
感谢作者，通过这个开源项目我学了不少东西，想请问下BottomNavigationView默认是不是只完整显示3个菜单啊？你这个默认显示4个设置是怎么实现的呢？我看了下代码没怎么看明白，大佬能不能写个文章介绍下啊

**Comment by iMeiji** [comment]
@jayleco 通过反射去改变每个 item 的 ShiftingMode 属性，这样超过3个menu也不会缩小，你可以看看 widget-helper-BottomNavigationViewHelper.java

**Comment by jayleco** [comment]
感谢大佬指点
