### ISSUE TITLE
主题色切换

### ISSUE THREAD

**Issue by lhzlg3368** [iMeiji/Toutiao#29]
请问下一条中的主题色是怎么切换的？
public void onColorSelection(@NonNull ColorChooserDialog dialog, @ColorInt int selectedColor)
方法中只有切换状态栏、任务栏、导航栏的颜色
请问是怎么动态切换主题色的？

**Comment by iMeiji** [comment]
```
@Override
    public void onResume() {
        super.onResume();
        linearLayout.setBackgroundColor(SettingUtil.getInstance().getColor());
    }
```

在 onResume 里重新设置颜色，但这么写部分机型可能会失效，正确写法是发送个 事件/广播 通知界面要更改颜色，可以看看我另一个项目 https://github.com/iMeiji/Daily
