### ISSUE TITLE
好奇怪啊，SdkManager这个类为啥在文件夹中找不到

### ISSUE THREAD

**Issue by ZhangPeng0220** [iMeiji/Toutiao#33]
在AS中能看到 这个类的代码，但是在目录中找不到这个文件

**Comment by ZhangPeng0220** [comment]
![image](https://user-images.githubusercontent.com/18100741/35953448-a502a71e-0cbf-11e8-9b37-6728420acbaa.png)

**Comment by shenqiwen** [comment]
@ZhangPeng0220 
![7 4t2_ xs5 tw 9 4h89x](https://user-images.githubusercontent.com/31466883/36009382-e2b68aea-0d86-11e8-8fb2-e8885e886221.png)
