### ISSUE TITLE
请问一下这个debug文件夹作用是什么，为什么要不把这个类直接放到main目录下，而是拿出来放在debug下面？？？还有就是这个debug目录是工具生成的嘛，还是自己手动添加的

### ISSUE THREAD

**Issue by ZhangPeng0220** [iMeiji/Toutiao#34]
![c j7 0lay fb6vul9 d o4](https://user-images.githubusercontent.com/18100741/36575450-fb91cb60-1885-11e8-9fdd-3e55bfd57d40.png)

**Comment by iMeiji** [comment]
@ZhangPeng0220 这叫 gradle 差异化构建，src 目录下的 debug，release 都是手动创建的，因为 `com.facebook.stetho:stetho` 和 `com.squareup.okhttp3:logging-interceptor` 是通过 debugCompile 方式引入，只会在 debug 版本引入，如果写在 main 目录下编译 release 版本就提示找不到该类

**Comment by ZhangPeng0220** [comment]
佩服，真是佩服
