### ISSUE TITLE
关于LazyLoadFragment的一些疑问

### ISSUE THREAD

**Issue by ZhangPeng0220** [iMeiji/Toutiao#37]
作者在onActivityCreated和setUserVisibleHint中都调用了prepareFetchData方法，
![pq8wd 1rw6n u8opok6c 5a](https://user-images.githubusercontent.com/18100741/36967196-0ca7de1e-209a-11e8-8490-d9900f024a3b.png)
但是我尝试打印了一下onActivityCreated和setUserVisibleHint两个方法的调用顺序，结果如图
![image](https://user-images.githubusercontent.com/18100741/36967292-49750d6c-209a-11e8-9e8b-4b8e61e34e7d.png)
也就是说setUserVisibleHint在调用prepareFetchData直接返回了false，请问这里重复调用的用意是什么呢，有什么特殊想法

**Comment by iMeiji** [comment]
@ZhangPeng0220 
来回切换 Fragment 的时候会不停调用 setUserVisibleHint  ， 而 onActivityCreated 在不重启生命周期的情况下只会加载一次。假如你去掉 setUserVisibleHint 里调用 prepareFetchData 这行代码，那么你从 tab1 滑动到 tab2 的时候，tab2 的 onActivityCreated 早就加载过了，谁去调用 prepareFetchData ？

更准确的写法是：
```
@Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        this.isVisibleToUser = isVisibleToUser;
        if (isVisibleToUser) {
            prepareFetchData();
        }
    }
```

**Comment by ZhangPeng0220** [comment]
那就是说，无论初始化程序的时候和切换fragment的时候，都会调用到prepareFetchData，那为什么还要在onActivityCreated 中加载呢，只是用setUserVisibleHint 不就好了吗

**Comment by iMeiji** [comment]
@ZhangPeng0220 你没搞懂什么是懒加载，建议你看看相关文章
