### ISSUE TITLE
错误: 不兼容的类型: View无法转换为TextView/ImageView

### ISSUE THREAD

**Issue by CoderBeanLiang** [iMeiji/Toutiao#4]
为什么所有的Adapter和ViewHolder类都会提示这个错误，我看了下源码中这些地方使用findViewById后并没有做强制类型转换，按理说这样写运行是通不过的，那为什么项目里会这样写呢

**Comment by iMeiji** [comment]
你确定使用最新的SDK26了？SDK26 更新了findViewById 不需要强制转型了

**Comment by CoderBeanLiang** [comment]
多谢解答~
确实是我这边降低SDK了
