### ISSUE TITLE
关于参数as,cp的问题

### ISSUE THREAD

**Issue by wgscd** [iMeiji/Toutiao#49]
例如获取 头条好文章
https://www.toutiao.com/pgc/ma/?media_id=323259752466666&page_type=1&max_behot_time=0&count=10&version=2&platform=pc&as=A1C548D5FDB17E6&cp=585DB1871ED64E1

有没有参数as,cp提供生成方法的说明。。。
不然请求都会是没有数据

**Comment by iMeiji** [comment]
https://github.com/iMeiji/Toutiao/blob/master/app/src/main/java/com/meiji/toutiao/util/ToutiaoUtil.java

**Comment by wgscd** [comment]
thanks very munch !
