### ISSUE TITLE
MainActivity中屏幕恢复时取出位置这个不太准确。

### ISSUE THREAD

**Issue by geogie** [iMeiji/Toutiao#5]
测试机型：小米 MI5 7.0 
1、屏幕旋转时并没有执行onSaveInstanceState，也没有执行：if (savedInstanceState != null) 里的代码。
2、按home键：执行了onSaveInstanceState，回到前台并没有执行if (savedInstanceState != null) 里的代码。
3、recreate();执行后，先执行了onSaveInstanceState，后执行了if (savedInstanceState != null) 里的代码。
总结：
1、这部分现场保护机制在recreate(); 起作用了。
2、屏幕旋转：并没有起到作用。
3、当然官网说的那种...becomes vulnerable to being destroyed by the system...没有测到。
这个注释“屏幕旋转时记录位置”感觉很迷惑。或者是和我的测试机有关？

**Comment by iMeiji** [comment]
@geogie 你把 Manifest 里 MainActivity 去掉 android:configChanges属性, 再旋转屏幕就会恢复当前位置了, 但这么做 Fragment 的数据无法保留

**Comment by geogie** [comment]
@iMeiji 谢谢大神，的确，去掉 android:configChanges属性后，那个恢复现场的逻辑走通了。
我看了下你项目里没有去掉那个config配置。
1、目前你的项目里有这个config，那么这个恢复现场的逻辑就对“屏幕旋转时记录位置”不起作用了，哈哈，所以我就迷茫了。
谢谢释疑。感觉把那句注释“屏幕旋转时记录位置”去掉就好懂了，哈哈
