### ISSUE TITLE
编译报错Unable to resolve dependency for

### ISSUE THREAD

**Issue by PranceLi** [iMeiji/Toutiao#57]
所有的依赖都会报错，无法编译过，请教下怎么解决
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.squareup.okhttp3:logging-interceptor:3.10.0.
<img width="1187" alt="machi 2019-01-19 22-07-49" src="https://user-images.githubusercontent.com/5248978/51427794-ad21dc80-1c36-11e9-804a-a1222f7646d6.png">

**Comment by iMeiji** [comment]
@PranceLi 
更新下代码，然后 Settings -> Build … -> Gradle -> Android Studio -> Enable embedded maven repository
