### ISSUE TITLE
头条数据获取失败

### ISSUE THREAD

**Issue by Quilljou** [iMeiji/Toutiao#9]
头条的新闻标题数据貌似需要携带cookie才可以拿到，但是你的代码中貌似没有看到有携带cookie？

**Comment by iMeiji** [comment]
@Quilljou 不一定需要 cookie ，如果你需要头条的智能推送新闻那就需要登录的 cookie

**Comment by Quilljou** [comment]
http://m.toutiao.com/list/?tag=news_society&ac=wap&count=20&format=json_raw&as=A17538D54D106FF&cp=585DF0A65F0F1E1&min_behot_time=0
比如这个接口，不加cookie的情况下能够拿到数据成功率非常低。
这个cookie是访问m.toutiao.com时候返回的

**Comment by iMeiji** [comment]
@Quilljou 你这个接口是从头条的移动版抓取的，我的接口是从客户端抓取的，移动版的限制很多，我项目里并没有使用这个接口，还有 as 和 cp 值也是需要计算得到，不然也会失效
